fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
    versioning: true
    body_converter:
        enabled: true
        validate: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
    exception:
        enabled: true
        codes:
            App\Exception\RessourceValidationException: 400
        messages:
            App\Exception\RessourceValidationException: true
